
import { BlogPost, BlogCategory } from './types';

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: 'Getting Started With React',
    subtitle: 'Learn the Basics and Start Your React Journey',
    author: 'Alex Morgan',
    date: 'August 10, 2025',
    tags: ['React', 'Typescript', 'Tailwind'],
    category: BlogCategory.FRONTEND,
  },
  {
    id: 2,
    title: 'Advanced TypeScript Patterns',
    subtitle: 'Unlock the full potential of TypeScript with these powerful patterns.',
    author: 'Samantha Bee',
    date: 'August 13, 2025',
    tags: ['TypeScript', 'Next.js', 'JavaScript'],
    category: BlogCategory.FRONTEND,
  },
  {
    id: 3,
    title: 'UI Design With Tailwind CSS',
    subtitle: 'Build beautiful, custom designs without leaving your HTML.',
    author: 'John Doe',
    date: 'August 17, 2025',
    tags: ['Tailwind', 'React'],
    category: BlogCategory.FRONTEND,
  },
  {
    id: 8,
    title: 'State Management with Zustand',
    subtitle: 'A simple and powerful state management solution for React.',
    author: 'John Doe',
    date: 'August 20, 2025',
    tags: ['React', 'Zustand', 'State Management'],
    category: BlogCategory.FRONTEND,
  },
  {
    id: 9,
    title: 'Animations with Framer Motion',
    subtitle: 'Bring your React apps to life with beautiful animations.',
    author: 'Samantha Bee',
    date: 'August 22, 2025',
    tags: ['React', 'Framer Motion', 'Animation'],
    category: BlogCategory.FRONTEND,
  },
  {
    id: 10,
    title: 'Introduction to SvelteKit',
    subtitle: 'Building fast and robust web applications with Svelte.',
    author: 'Alex Morgan',
    date: 'August 25, 2025',
    tags: ['Svelte', 'SvelteKit', 'JavaScript'],
    category: BlogCategory.FRONTEND,
  },
  {
    id: 5,
    title: 'Building REST APIs with Node.js',
    subtitle: 'A practical guide to creating powerful APIs with Node.js and Express.',
    author: 'Alex Morgan',
    date: 'August 10, 2025',
    tags: ['Node.js', 'Express.js'],
    category: BlogCategory.BACKEND,
  },
  {
    id: 6,
    title: 'Scaling Applications with Microservices',
    subtitle: 'Understand the benefits and challenges of a microservice architecture.',
    author: 'Jane Smith',
    date: 'August 13, 2025',
    tags: ['Express.js', 'Docker', 'Kubernetes'],
    category: BlogCategory.BACKEND,
  },
  {
    id: 7,
    title: 'Building GraphQL APIs with NestJS',
    subtitle: 'Leverage NestJS to build efficient and scalable GraphQL APIs.',
    author: 'Samantha Bee',
    date: 'August 17, 2025',
    tags: ['NestJS', 'Database', 'GraphQL'],
    category: BlogCategory.BACKEND,
  },
  {
    id: 11,
    title: 'Working with Databases in Go',
    subtitle: 'A guide to connecting and querying databases using Go.',
    author: 'Jane Smith',
    date: 'August 21, 2025',
    tags: ['Go', 'Databases', 'SQL'],
    category: BlogCategory.BACKEND,
  },
  {
    id: 12,
    title: 'Authentication with JWT',
    subtitle: 'Secure your APIs with JSON Web Tokens.',
    author: 'Alex Morgan',
    date: 'August 24, 2025',
    tags: ['JWT', 'Authentication', 'Security'],
    category: BlogCategory.BACKEND,
  },
  {
    id: 13,
    title: 'Serverless Functions with AWS Lambda',
    subtitle: 'Deploying and managing serverless applications on AWS.',
    author: 'John Doe',
    date: 'August 28, 2025',
    tags: ['AWS', 'Lambda', 'Serverless'],
    category: BlogCategory.BACKEND,
  },
];

export const CATEGORIES = ['All', ...Object.values(BlogCategory)];